### ISSUE TITLE
InAppBrowser not closing

### ISSUE THREAD

**Issue by pragyesh12** [magiclabs/react-native-demo#49]
In MagicBareRnExample when we try to login with google inapp browser open and loader keeps loading its doesn't route back to login screen.

Plantform: Android

 <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="sponsors" />
 </intent-filter> 
 
 Method
  const googleData = await magicNative.oauth.loginWithPopup({
          provider: 'google',
          redirectURI: 'sponsors://',
   });

**Comment by pragyesh12** [comment]
Hey @Ariflo any update on this?

**Comment by Ariflo** [comment]
@pragyesh12 We are still investigating. Apologies for the delay. We will do our best to get this resolved asap
